import fs from "fs";
import path from "path";

const dictsDir = path.join(process.cwd(), "lib", "i18n", "dictionaries");

const translations: Record<string, any> = {
  "en-NG": {
    dashboardShowcase: {
      eyebrow: "Live Interactive Workspace Preview",
      title: "See KoraSpace in action:",
      subtitle: "Switch between Creator Mode and Marketer Mode to preview how KoraSpace adapts to your workflow.",
      creatorMode: "Creator Studio",
      marketerMode: "Marketing Operator",
      composerTitle: "AI Composing Pipeline",
      composerDesc: "8-step voice matching, draft scoring & reflections.",
      calendarTitle: "Visual 6-Platform Calendar",
      calendarDesc: "Drag-and-drop scheduling across Instagram, TikTok, LinkedIn, YouTube, X & Threads.",
      crmTitle: "Social CRM & Lead Triage",
      crmDesc: "Detect high-intent buying signals in DMs & comments.",
      pipelineScore: "KoraScore 88/100",
      engagementRate: "3.8% Engagement Rate",
      revenueAttributed: "₦12.4M Pipeline Revenue",
      previewMode: "Mode",
      aiStudio: "AI Studio",
      visualCalendar: "Visual Calendar",
      viralTrends: "Viral Trends",
      repurpose: "Repurpose",
      audience: "Audience",
      brandKit: "Brand Kit",
      realTimeSync: "Real-time Sync",
      totalReach: "Total Reach",
      engagement: "Engagement",
      scheduled: "Scheduled",
      allSynced: "All synced",
      aiContentScore: "AI Content Score",
      optimalVoice: "Optimal voice",
      activeAiGeneration: "Active AI Generation • Signature Brand Voice",
      hookPreview: "Hook: 3 AI strategies modern creators are using to scale audience in 2026. Most creators focus on raw volume. The top 1% build repeatable audience loops. Here is the 4-step framework we used to 10x distribution while cutting editing time in half...",
      eightStepReflection: "8-step brand reflection passed",
      scheduleToPlatforms: "Schedule to 5 Platforms",
      unifiedIntelligenceCloud: "Unified Intelligence Cloud",
      fasterContentSpeed: "10× Faster Content Speed",
      fasterContentDesc: "From idea to 6-platform draft in seconds",
      managedPipelineRevenue: "₦8.4M+ Managed Pipeline Revenue",
      managedPipelineDesc: "Attributed social sales and conversions",
      higherLeadIntent: "4.2× Higher Lead Intent",
      higherLeadDesc: "Automated comment & DM lead classification",
      connectedNetworks: "6+ Connected Networks",
      connectedNetworksDesc: "Instagram, TikTok, LinkedIn, YouTube, X, Threads",
      agentOperator: "Agent Operator",
      campaigns: "Campaigns",
      crmLeads: "CRM & Leads",
      automations: "Automations",
      attribution: "Attribution",
      strategy: "Strategy",
    },
    authLayout: {
      commandCenter: "Your marketing & creator command center",
      titleStart: "Turn your audience",
      titleHighlight: "into momentum.",
      description: "Manage multi-channel campaigns, draft in your signature brand voice, automate CRM workflows, and track real revenue growth across your accounts.",
      feature1: "Multi-channel workflows",
      feature2: "AI-powered intelligence",
      feature3: "Real-time attribution",
      secureCloud: "Secure Cloud Workspace",
      workspaceCommand: "Workspace Command Center",
      overview: "Overview",
      create: "Create",
      campaignsNav: "Campaigns",
      analytics: "Analytics",
      crmNav: "CRM & Leads",
      brandKitNav: "Brand Kit",
      settings: "Settings",
      revenue: "Revenue",
      roas: "ROAS",
      leads: "Leads",
      growth: "Growth",
    },
    authPages: {
      loginTitle: "Welcome back",
      loginSubtitle: "Sign in to access your KoraSpace workspace and live campaigns.",
      signupTitle: "Create your account",
      signupSubtitle: "Start your autonomous growth journey today.",
      emailLabel: "Email address",
      passwordLabel: "Password",
      nameLabel: "Full name",
      loginButton: "Sign in",
      signupButton: "Create account",
      googleButton: "Continue with Google",
      noAccount: "Don't have an account?",
      haveAccount: "Already have an account?",
      forgotPassword: "Forgot password?",
      marketingSuite: "Marketing & Creator Suite",
    }
  },
  "es": {
    dashboardShowcase: {
      eyebrow: "Vista Previa Interactiva",
      title: "Vea KoraSpace en acción:",
      subtitle: "Cambie entre el Modo Creador y el Operador de Marketing para ver cómo KoraSpace se adapta a su flujo.",
      creatorMode: "Estudio de Creadores",
      marketerMode: "Operador de Marketing",
      composerTitle: "Canalización de IA",
      composerDesc: "Coincidencia de voz de 8 pasos, puntuación de borradores y reflexiones.",
      calendarTitle: "Calendario Visual (6 Plataformas)",
      calendarDesc: "Programación en Instagram, TikTok, LinkedIn, YouTube, X y Threads.",
      crmTitle: "CRM Social y Leads",
      crmDesc: "Detecte señales de compra de alta intención en DMs y comentarios.",
      pipelineScore: "KoraScore 88/100",
      engagementRate: "3.8% Tasa de Interacción",
      revenueAttributed: "€12,450 Ingresos de Pipeline",
      previewMode: "Modo",
      aiStudio: "Estudio IA",
      visualCalendar: "Calendario",
      viralTrends: "Tendencias",
      repurpose: "Reutilizar",
      audience: "Audiencia",
      brandKit: "Kit de Marca",
      realTimeSync: "Sincronización Real",
      totalReach: "Alcance Total",
      engagement: "Interacción",
      scheduled: "Programado",
      allSynced: "Todo sincronizado",
      aiContentScore: "Puntaje IA",
      optimalVoice: "Voz óptima",
      activeAiGeneration: "Generación IA Activa • Voz Exclusiva",
      hookPreview: "Gancho: 3 estrategias de IA que los creadores modernos utilizan para escalar su audiencia. El 1% superior construye bucles repetibles. Aquí tienes el sistema de 4 pasos...",
      eightStepReflection: "Reflexión de 8 pasos completada",
      scheduleToPlatforms: "Programar en 5 plataformas",
      unifiedIntelligenceCloud: "Nube de Inteligencia Unificada",
      fasterContentSpeed: "10× Velocidad de Contenido",
      fasterContentDesc: "De idea a borrador en segundos",
      managedPipelineRevenue: "€8.4M+ Ingresos Gestionados",
      managedPipelineDesc: "Ventas y conversiones atribuidas a redes",
      higherLeadIntent: "4.2× Mayor Intención",
      higherLeadDesc: "Clasificación automática de leads en DM",
      connectedNetworks: "6+ Redes Conectadas",
      connectedNetworksDesc: "Instagram, TikTok, LinkedIn, YouTube, X, Threads",
      agentOperator: "Agente Operador",
      campaigns: "Campañas",
      crmLeads: "CRM y Leads",
      automations: "Automatizaciones",
      attribution: "Atribución",
      strategy: "Estrategia"
    },
    authLayout: {
      commandCenter: "Su centro de mando de marketing y creadores",
      titleStart: "Convierta su audiencia",
      titleHighlight: "en impulso.",
      description: "Gestione campañas multicanal, redacte con su voz de marca, automatice flujos CRM y rastree ingresos reales.",
      feature1: "Flujos multicanal",
      feature2: "Inteligencia impulsada por IA",
      feature3: "Atribución en tiempo real",
      secureCloud: "Espacio en la Nube Seguro",
      workspaceCommand: "Centro de Mando",
      overview: "Resumen",
      create: "Crear",
      campaignsNav: "Campañas",
      analytics: "Analítica",
      crmNav: "CRM y Leads",
      brandKitNav: "Kit de Marca",
      settings: "Ajustes",
      revenue: "Ingresos",
      roas: "ROAS",
      leads: "Leads",
      growth: "Crecimiento"
    },
    authPages: {
      loginTitle: "Bienvenido de nuevo",
      loginSubtitle: "Inicie sesión para acceder a su espacio KoraSpace.",
      signupTitle: "Cree su cuenta",
      signupSubtitle: "Comience su viaje de crecimiento autónomo hoy.",
      emailLabel: "Correo electrónico",
      passwordLabel: "Contraseña",
      nameLabel: "Nombre completo",
      loginButton: "Iniciar sesión",
      signupButton: "Crear cuenta",
      googleButton: "Continuar con Google",
      noAccount: "¿No tienes cuenta?",
      haveAccount: "¿Ya tienes cuenta?",
      forgotPassword: "¿Olvidó su contraseña?",
      marketingSuite: "Suite de Marketing y Creadores"
    }
  },
  "fr": {
    dashboardShowcase: {
      eyebrow: "Aperçu Interactif du Tableau de Bord",
      title: "Voir KoraSpace en action :",
      subtitle: "Basculez entre le mode Créateur et le mode Marketeur pour découvrir KoraSpace.",
      creatorMode: "Studio Créateur",
      marketerMode: "Opérateur Marketing",
      composerTitle: "Pipeline de Création IA",
      composerDesc: "8 étapes de correspondance vocale, score et réflexions.",
      calendarTitle: "Calendrier Visuel",
      calendarDesc: "Planification par glisser-déposer sur 6 plateformes.",
      crmTitle: "CRM Social & Leads",
      crmDesc: "Détectez les signaux d'achat dans les DMs et commentaires.",
      pipelineScore: "KoraScore 88/100",
      engagementRate: "3.8% Taux d'engagement",
      revenueAttributed: "12 450 € de revenus générés",
      previewMode: "Mode",
      aiStudio: "Studio IA",
      visualCalendar: "Calendrier Visuel",
      viralTrends: "Tendances Virales",
      repurpose: "Recycler",
      audience: "Audience",
      brandKit: "Kit de Marque",
      realTimeSync: "Sync. en temps réel",
      totalReach: "Portée Totale",
      engagement: "Engagement",
      scheduled: "Programmé",
      allSynced: "Tout synchronisé",
      aiContentScore: "Score de Contenu IA",
      optimalVoice: "Voix optimale",
      activeAiGeneration: "Génération IA Active • Voix de marque",
      hookPreview: "Accroche : 3 stratégies IA que les créateurs utilisent en 2026 pour croître. Voici la méthode en 4 étapes pour 10x votre distribution...",
      eightStepReflection: "Réflexion en 8 étapes terminée",
      scheduleToPlatforms: "Planifier sur 5 Plateformes",
      unifiedIntelligenceCloud: "Cloud d'Intelligence Unifié",
      fasterContentSpeed: "10× Plus de Vitesse",
      fasterContentDesc: "De l'idée au brouillon sur 6 réseaux en quelques secondes",
      managedPipelineRevenue: "8.4M€+ de Revenus",
      managedPipelineDesc: "Ventes et conversions sociales attribuées",
      higherLeadIntent: "4.2× Plus d'Intention",
      higherLeadDesc: "Classification automatisée des leads en DM",
      connectedNetworks: "6+ Réseaux Connectés",
      connectedNetworksDesc: "Instagram, TikTok, LinkedIn, YouTube, X, Threads",
      agentOperator: "Agent Opérateur",
      campaigns: "Campagnes",
      crmLeads: "CRM & Leads",
      automations: "Automatisations",
      attribution: "Attribution",
      strategy: "Stratégie"
    },
    authLayout: {
      commandCenter: "Votre centre de commande marketing & créateur",
      titleStart: "Transformez votre audience",
      titleHighlight: "en élan.",
      description: "Gérez des campagnes multicanales, rédigez avec votre voix de marque et suivez les revenus.",
      feature1: "Flux de travail multicanaux",
      feature2: "Intelligence par IA",
      feature3: "Attribution en temps réel",
      secureCloud: "Espace Cloud Sécurisé",
      workspaceCommand: "Centre de Commande",
      overview: "Aperçu",
      create: "Créer",
      campaignsNav: "Campagnes",
      analytics: "Analytique",
      crmNav: "CRM & Leads",
      brandKitNav: "Kit de Marque",
      settings: "Paramètres",
      revenue: "Revenus",
      roas: "ROAS",
      leads: "Leads",
      growth: "Croissance"
    },
    authPages: {
      loginTitle: "Bon retour",
      loginSubtitle: "Connectez-vous pour accéder à KoraSpace.",
      signupTitle: "Créer un compte",
      signupSubtitle: "Commencez votre croissance autonome aujourd'hui.",
      emailLabel: "Adresse e-mail",
      passwordLabel: "Mot de passe",
      nameLabel: "Nom complet",
      loginButton: "Se connecter",
      signupButton: "Créer le compte",
      googleButton: "Continuer avec Google",
      noAccount: "Pas encore de compte ?",
      haveAccount: "Vous avez déjà un compte ?",
      forgotPassword: "Mot de passe oublié ?",
      marketingSuite: "Suite Marketing & Créateur"
    }
  },
  "nl": {
    dashboardShowcase: {
      eyebrow: "Live Interactieve Preview",
      title: "Bekijk KoraSpace in actie:",
      subtitle: "Schakel tussen de Creator Modus en de Marketing Operator.",
      creatorMode: "Creator Studio",
      marketerMode: "Marketing Operator",
      composerTitle: "AI Pijplijn",
      composerDesc: "8-stappen stem afstemming en reflectie.",
      calendarTitle: "Visuele Kalender",
      calendarDesc: "Plan overal: Instagram, TikTok, LinkedIn, YouTube, X & Threads.",
      crmTitle: "Social CRM & Leads",
      crmDesc: "Detecteer hoge intentie in DMs en reacties.",
      pipelineScore: "KoraScore 88/100",
      engagementRate: "3.8% Betrokkenheid",
      revenueAttributed: "€12.450 Omzet",
      previewMode: "Modus",
      aiStudio: "AI Studio",
      visualCalendar: "Visuele Kalender",
      viralTrends: "Virale Trends",
      repurpose: "Hergebruiken",
      audience: "Publiek",
      brandKit: "Merkkit",
      realTimeSync: "Real-time Sync",
      totalReach: "Totaal Bereik",
      engagement: "Betrokkenheid",
      scheduled: "Gepland",
      allSynced: "Alles gesynchroniseerd",
      aiContentScore: "AI Content Score",
      optimalVoice: "Optimale stem",
      activeAiGeneration: "Actieve AI Generatie",
      hookPreview: "Hook: 3 AI-strategieën die creators in 2026 gebruiken. Hier is het 4-stappen raamwerk...",
      eightStepReflection: "8-stappen reflectie geslaagd",
      scheduleToPlatforms: "Plan naar 5 Platforms",
      unifiedIntelligenceCloud: "Verenigde Intelligentie",
      fasterContentSpeed: "10× Snellere Content",
      fasterContentDesc: "Van idee naar draft in seconden",
      managedPipelineRevenue: "€8.4M+ Omzet",
      managedPipelineDesc: "Toegeschreven sociale verkopen",
      higherLeadIntent: "4.2× Hogere Intentie",
      higherLeadDesc: "Geautomatiseerde DM classificatie",
      connectedNetworks: "6+ Netwerken",
      connectedNetworksDesc: "Instagram, TikTok, LinkedIn, YouTube, X, Threads",
      agentOperator: "Agent Operator",
      campaigns: "Campagnes",
      crmLeads: "CRM & Leads",
      automations: "Automatiseringen",
      attribution: "Attributie",
      strategy: "Strategie"
    },
    authLayout: {
      commandCenter: "Jouw marketing commandocentrum",
      titleStart: "Verander je publiek",
      titleHighlight: "in momentum.",
      description: "Beheer multi-channel campagnes en automatiseer CRM workflows.",
      feature1: "Multi-channel workflows",
      feature2: "AI-intelligentie",
      feature3: "Real-time attributie",
      secureCloud: "Veilige Cloud Werkruimte",
      workspaceCommand: "Werkruimte",
      overview: "Overzicht",
      create: "Creëren",
      campaignsNav: "Campagnes",
      analytics: "Analyses",
      crmNav: "CRM & Leads",
      brandKitNav: "Merkkit",
      settings: "Instellingen",
      revenue: "Omzet",
      roas: "ROAS",
      leads: "Leads",
      growth: "Groei"
    },
    authPages: {
      loginTitle: "Welkom terug",
      loginSubtitle: "Log in om toegang te krijgen tot KoraSpace.",
      signupTitle: "Maak een account aan",
      signupSubtitle: "Begin vandaag nog met je autonome groei.",
      emailLabel: "E-mailadres",
      passwordLabel: "Wachtwoord",
      nameLabel: "Volledige naam",
      loginButton: "Inloggen",
      signupButton: "Account aanmaken",
      googleButton: "Doorgaan met Google",
      noAccount: "Nog geen account?",
      haveAccount: "Heb je al een account?",
      forgotPassword: "Wachtwoord vergeten?",
      marketingSuite: "Marketing & Creator Suite"
    }
  },
  "zh": {
    dashboardShowcase: {
      eyebrow: "实时交互式工作区预览",
      title: "看看 KoraSpace 是如何工作的：",
      subtitle: "在创作者模式和营销操作员之间切换，预览您的工作流。",
      creatorMode: "创作者工作室",
      marketerMode: "营销操作员",
      composerTitle: "AI 写作流水线",
      composerDesc: "8步品牌语调匹配、文案打分与反思。",
      calendarTitle: "可视化日历",
      calendarDesc: "跨 Instagram、TikTok、LinkedIn 等平台的拖放调度。",
      crmTitle: "社交 CRM 与线索",
      crmDesc: "在私信和评论中检测高意向购买信号。",
      pipelineScore: "KoraScore 88/100",
      engagementRate: "3.8% 互动率",
      revenueAttributed: "¥85,450 归因收入",
      previewMode: "模式",
      aiStudio: "AI 工作室",
      visualCalendar: "可视化日历",
      viralTrends: "热门趋势",
      repurpose: "内容重用",
      audience: "受众",
      brandKit: "品牌工具包",
      realTimeSync: "实时同步",
      totalReach: "总曝光",
      engagement: "互动率",
      scheduled: "已排期",
      allSynced: "已全同步",
      aiContentScore: "AI 内容评分",
      optimalVoice: "最优语调",
      activeAiGeneration: "活跃 AI 生成 • 标志性品牌声音",
      hookPreview: "钩子：现代创作者在2026年用来扩大受众的3个AI策略。这就是我们用来使分发量增加10倍的4步框架...",
      eightStepReflection: "已通过8步品牌反思",
      scheduleToPlatforms: "排期至 5 个平台",
      unifiedIntelligenceCloud: "统一智能云",
      fasterContentSpeed: "10倍的内容生成速度",
      fasterContentDesc: "从想法到 6 平台草稿只需几秒钟",
      managedPipelineRevenue: "¥58.4M+ 管理流水收入",
      managedPipelineDesc: "归因的社交销售和转化",
      higherLeadIntent: "4.2倍更高的线索意向",
      higherLeadDesc: "自动化的评论和 DM 线索分类",
      connectedNetworks: "6+ 个连接网络",
      connectedNetworksDesc: "Instagram, TikTok, LinkedIn, YouTube, X, Threads",
      agentOperator: "代理操作员",
      campaigns: "活动",
      crmLeads: "CRM 与线索",
      automations: "自动化",
      attribution: "归因",
      strategy: "策略"
    },
    authLayout: {
      commandCenter: "您的营销和创作者指挥中心",
      titleStart: "将您的受众",
      titleHighlight: "转化为动力。",
      description: "管理多渠道活动，用您的标志性品牌声音起草文案，自动化 CRM 工作流，并跟踪真实收入增长。",
      feature1: "多渠道工作流",
      feature2: "AI 驱动的智能",
      feature3: "实时归因",
      secureCloud: "安全的云工作区",
      workspaceCommand: "工作区指挥中心",
      overview: "概览",
      create: "创建",
      campaignsNav: "活动",
      analytics: "分析",
      crmNav: "CRM 与线索",
      brandKitNav: "品牌包",
      settings: "设置",
      revenue: "收入",
      roas: "广告支出回报",
      leads: "线索",
      growth: "增长"
    },
    authPages: {
      loginTitle: "欢迎回来",
      loginSubtitle: "登录以访问您的 KoraSpace 工作区和实时活动。",
      signupTitle: "创建您的帐户",
      signupSubtitle: "今天就开始您的自主增长之旅。",
      emailLabel: "电子邮件地址",
      passwordLabel: "密码",
      nameLabel: "全名",
      loginButton: "登录",
      signupButton: "创建帐户",
      googleButton: "使用 Google 继续",
      noAccount: "没有帐户？",
      haveAccount: "已有帐户？",
      forgotPassword: "忘记密码？",
      marketingSuite: "营销与创作者套件"
    }
  },
  "ar": {
    dashboardShowcase: {
      eyebrow: "معاينة مساحة العمل التفاعلية الحية",
      title: "شاهد KoraSpace أثناء العمل:",
      subtitle: "بدل بين وضع منشئ المحتوى ووضع المسوق لمعاينة مساحة العمل.",
      creatorMode: "استوديو المبدعين",
      marketerMode: "المسوق الآلي",
      composerTitle: "أنبوب كتابة الذكاء الاصطناعي",
      composerDesc: "8 خطوات لمطابقة الصوت وتقييم المسودات.",
      calendarTitle: "تقويم مرئي لـ 6 منصات",
      calendarDesc: "جدولة بالسحب والإفلات عبر إنستجرام، تيك توك، وغيرها.",
      crmTitle: "إدارة علاقات العملاء والعملاء المحتملين",
      crmDesc: "اكتشف إشارات الشراء عالية النية في الرسائل المباشرة والتعليقات.",
      pipelineScore: "نقاط Kora 88/100",
      engagementRate: "3.8% معدل التفاعل",
      revenueAttributed: "45,850 د.إ إيرادات منسوبة",
      previewMode: "الوضع",
      aiStudio: "استوديو الذكاء الاصطناعي",
      visualCalendar: "التقويم المرئي",
      viralTrends: "الاتجاهات الشائعة",
      repurpose: "إعادة استخدام",
      audience: "الجمهور",
      brandKit: "مجموعة العلامة التجارية",
      realTimeSync: "مزامنة فورية",
      totalReach: "إجمالي الوصول",
      engagement: "التفاعل",
      scheduled: "المجدولة",
      allSynced: "متزامن بالكامل",
      aiContentScore: "نقاط محتوى الذكاء الاصطناعي",
      optimalVoice: "صوت مثالي",
      activeAiGeneration: "توليد نشط للذكاء الاصطناعي • صوت العلامة التجارية",
      hookPreview: "خطاف: 3 استراتيجيات للذكاء الاصطناعي يستخدمها المبدعون المعاصرون. هذا هو إطار العمل المكون من 4 خطوات...",
      eightStepReflection: "اجتاز 8 خطوات من انعكاس العلامة التجارية",
      scheduleToPlatforms: "الجدولة إلى 5 منصات",
      unifiedIntelligenceCloud: "سحابة الاستخبارات الموحدة",
      fasterContentSpeed: "10× سرعة محتوى أسرع",
      fasterContentDesc: "من فكرة إلى مسودة لـ 6 منصات في ثوانٍ",
      managedPipelineRevenue: "8.4M+ إيرادات مُدارة",
      managedPipelineDesc: "المبيعات والتحويلات الاجتماعية المنسوبة",
      higherLeadIntent: "4.2× نية عميل أعلى",
      higherLeadDesc: "تصنيف آلي للرسائل والتعليقات",
      connectedNetworks: "6+ شبكات متصلة",
      connectedNetworksDesc: "Instagram, TikTok, LinkedIn, YouTube, X, Threads",
      agentOperator: "الوكيل المشغل",
      campaigns: "الحملات",
      crmLeads: "العملاء المحتملين وإدارة العلاقات",
      automations: "الأتمتة",
      attribution: "الإسناد",
      strategy: "الاستراتيجية"
    },
    authLayout: {
      commandCenter: "مركز قيادة التسويق والمبدعين",
      titleStart: "حول جمهورك",
      titleHighlight: "إلى زخم.",
      description: "أدر الحملات متعددة القنوات، واكتب بصوت علامتك التجارية، وأتمت مسارات عمل إدارة علاقات العملاء.",
      feature1: "مسارات عمل متعددة القنوات",
      feature2: "ذكاء مدعوم بالذكاء الاصطناعي",
      feature3: "إسناد في الوقت الفعلي",
      secureCloud: "مساحة عمل سحابية آمنة",
      workspaceCommand: "مركز قيادة مساحة العمل",
      overview: "نظرة عامة",
      create: "إنشاء",
      campaignsNav: "الحملات",
      analytics: "التحليلات",
      crmNav: "العملاء وإدارة العلاقات",
      brandKitNav: "مجموعة العلامة التجارية",
      settings: "الإعدادات",
      revenue: "الإيرادات",
      roas: "عائد الإعلانات",
      leads: "العملاء المحتملين",
      growth: "النمو"
    },
    authPages: {
      loginTitle: "مرحباً بعودتك",
      loginSubtitle: "قم بتسجيل الدخول للوصول إلى مساحة عمل KoraSpace الخاصة بك.",
      signupTitle: "أنشئ حسابك",
      signupSubtitle: "ابدأ رحلة النمو المستقل اليوم.",
      emailLabel: "عنوان البريد الإلكتروني",
      passwordLabel: "كلمة المرور",
      nameLabel: "الاسم الكامل",
      loginButton: "تسجيل الدخول",
      signupButton: "إنشاء حساب",
      googleButton: "المتابعة باستخدام Google",
      noAccount: "ليس لديك حساب؟",
      haveAccount: "لديك حساب بالفعل؟",
      forgotPassword: "هل نسيت كلمة المرور؟",
      marketingSuite: "مجموعة التسويق والمبدعين"
    }
  }
};

const mapVar: Record<string, string> = {
  "en-NG": "enNG",
  es: "es",
  fr: "fr",
  nl: "nl",
  zh: "zh",
  ar: "ar",
  "en-US": "enUS"
};

Object.entries(translations).forEach(([locale, newKeys]) => {
  const filePath = path.join(dictsDir, `${locale}.ts`);
  if (fs.existsSync(filePath)) {
    let content = fs.readFileSync(filePath, "utf-8");
    
    // Clear out old ones if any
    content = content.replace(/dashboardShowcase:\s*\{[\s\S]*?\},/, "");
    content = content.replace(/authLayout:\s*\{[\s\S]*?\},/, "");
    content = content.replace(/authPages:\s*\{[\s\S]*?\},/, "");
    
    const newKeysString = Object.entries(newKeys).map(([key, value]) => {
      const stringifiedValue = JSON.stringify(value, null, 2)
        .replace(/"([^"]+)":/g, '$1:');
      return `  ${key}: ${stringifiedValue},`;
    }).join("\n");

    const varName = mapVar[locale] || locale.replace("-", "");
    
    // Check if it exports dict or the specific var
    if (content.includes(`export const dict: TranslationDictionary`)) {
      content = content.replace(`export const dict: TranslationDictionary = {`, `export const dict: TranslationDictionary = {\n${newKeysString}`);
    } else {
      content = content.replace(`export const ${varName}: TranslationDictionary = {`, `export const ${varName}: TranslationDictionary = {\n${newKeysString}`);
    }
    
    fs.writeFileSync(filePath, content);
    console.log(`Updated ${locale}.ts`);
  }
});
