"use client";

import { useState } from "react";
import {
  Sparkles,
  Copy,
  Pencil,
  WandSparkles,
  Check,
  MoreHorizontal,
  ArrowRight,
} from "lucide-react";

import { MarkdownRenderer } from "@/components/dashboard/MarkdownRenderer";

interface AiDraftCardProps {
  content?: string;
  hashtags?: string[];
  isGenerating?: boolean;
  onImprove?: () => void;
  onEdit?: () => void;
  onUse?: () => void;
}

export function AiDraftCard({
  content,
  hashtags = [],
  isGenerating = false,
  onImprove,
  onEdit,
  onUse,
}: AiDraftCardProps) {
  const [copied, setCopied] = useState(false);

  const handleCopy = async () => {
    if (!content) return;
    const text = hashtags.length
      ? `${content}\n\n${hashtags.map((t) => `#${t.replace("#", "")}`).join(" ")}`
      : content;
    await navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  /* ── Skeleton ── */
  if (isGenerating) {
    return (
      <section className="min-h-[420px] rounded-2xl border border-[var(--stroke)] bg-[var(--panel-fill)] p-5">
        <div className="mb-8 flex justify-between">
          <div className="flex items-center gap-3">
            <div className="h-7 w-7 rounded-lg bg-[var(--kora-blue-soft)] skeleton-shimmer" />
            <div className="space-y-1.5">
              <div className="h-3.5 w-20 rounded bg-[var(--panel-fill-2)] skeleton-shimmer" />
              <div className="h-2.5 w-28 rounded bg-[var(--panel-fill-2)] skeleton-shimmer" />
            </div>
          </div>
        </div>
        <div className="space-y-3">
          {[100, 90, 75, 60, 80, 55].map((w, i) => (
            <div
              key={i}
              className="h-3.5 rounded skeleton-shimmer"
              style={{ width: `${w}%` }}
            />
          ))}
        </div>

        {/* Kora thinking state */}
        <div className="mt-8 space-y-2.5">
          {[
            { label: "Understanding your idea", done: true },
            { label: "Checking your brand voice", done: true },
            { label: "Finding the right angle", done: false },
            { label: "Writing your content", done: false },
          ].map((step, i) => (
            <div key={i} className="flex items-center gap-2.5 text-[11px]">
              {step.done ? (
                <Check className="h-3.5 w-3.5 text-[var(--success)]" />
              ) : (
                <span className="flex h-3.5 w-3.5 items-center justify-center">
                  <span className="h-1.5 w-1.5 animate-bounce rounded-full bg-[var(--kora-blue)]" style={{ animationDelay: `${i * 0.15}s` }} />
                </span>
              )}
              <span className={step.done ? "text-[var(--fg-3)]" : "text-[var(--kora-blue)]"}>
                {step.label}
              </span>
            </div>
          ))}
        </div>
      </section>
    );
  }

  /* ── Empty state ── */
  if (!content) {
    return (
      <section className="flex min-h-[420px] flex-col items-center justify-center rounded-2xl border border-dashed border-[var(--stroke-strong)] bg-[var(--panel-fill)] p-8 text-center">
        <div className="mb-4 flex h-12 w-12 items-center justify-center rounded-2xl bg-[var(--kora-blue-soft)] text-[var(--kora-blue)]">
          <Sparkles className="h-5 w-5" />
        </div>
        <h3 className="text-[15px] font-semibold text-[var(--fg)]">
          Your AI draft will appear here
        </h3>
        <p className="mt-2 max-w-[260px] text-[12px] leading-relaxed text-[var(--fg-4)]">
          Tell Kora what you want to create and we&apos;ll turn your idea into
          content.
        </p>
      </section>
    );
  }

  /* ── Draft ── */
  return (
    <section className="overflow-hidden rounded-2xl border border-[var(--stroke)] bg-[var(--panel-fill)]">
      {/* Header */}
      <div className="flex items-center justify-between border-b border-[var(--stroke)] px-5 py-4">
        <div className="flex items-center gap-2.5">
          <div className="flex h-7 w-7 items-center justify-center rounded-lg bg-[var(--kora-blue-soft)] text-[var(--kora-blue)]">
            <Sparkles className="h-3.5 w-3.5" />
          </div>
          <div>
            <p className="text-[13px] font-semibold text-[var(--fg)]">AI Draft</p>
            <p className="text-[10px] text-[var(--fg-4)]">Generated by Kora AI</p>
          </div>
        </div>
        <button className="flex h-8 w-8 items-center justify-center rounded-lg text-[var(--fg-4)] hover:bg-[var(--hover)] hover:text-[var(--fg)]">
          <MoreHorizontal className="h-4 w-4" />
        </button>
      </div>

      {/* Content */}
      <div className="p-5">
        <div className="text-[13px] leading-[1.8] text-[var(--fg-2)]">
          <MarkdownRenderer content={content} />
        </div>

        {hashtags.length > 0 && (
          <div className="mt-5 flex flex-wrap gap-2">
            {hashtags.map((tag) => (
              <span
                key={tag}
                className="rounded-lg bg-[var(--kora-blue-soft)] px-2.5 py-1.5 text-[10.5px] text-[var(--kora-blue)]"
              >
                #{tag.replace("#", "")}
              </span>
            ))}
          </div>
        )}
      </div>

      {/* Actions */}
      <div className="border-t border-[var(--stroke)] p-4">
        <div className="flex flex-wrap items-center gap-2">
          <button
            onClick={onImprove}
            className="flex items-center gap-2 rounded-lg border border-[var(--stroke)] px-3 py-2 text-[11px] font-medium text-[var(--fg-3)] transition-colors hover:bg-[var(--hover)] hover:text-[var(--fg)]"
          >
            <WandSparkles className="h-3.5 w-3.5 text-[var(--kora-blue)]" />
            Improve
          </button>

          <button
            onClick={onEdit}
            className="flex items-center gap-2 rounded-lg border border-[var(--stroke)] px-3 py-2 text-[11px] font-medium text-[var(--fg-3)] transition-colors hover:bg-[var(--hover)] hover:text-[var(--fg)]"
          >
            <Pencil className="h-3.5 w-3.5" />
            Edit
          </button>

          <button
            onClick={handleCopy}
            className="flex items-center gap-2 rounded-lg border border-[var(--stroke)] px-3 py-2 text-[11px] font-medium text-[var(--fg-3)] transition-colors hover:bg-[var(--hover)] hover:text-[var(--fg)]"
          >
            {copied ? (
              <>
                <Check className="h-3.5 w-3.5 text-[var(--success)]" />
                Copied
              </>
            ) : (
              <>
                <Copy className="h-3.5 w-3.5" />
                Copy
              </>
            )}
          </button>

          <button
            onClick={onUse}
            className="ml-auto flex items-center gap-2 rounded-lg bg-[var(--kora-pink)] px-4 py-2 text-[11px] font-semibold text-white transition-all hover:brightness-110 active:scale-[0.98]"
          >
            Use this
            <ArrowRight className="h-3.5 w-3.5" />
          </button>
        </div>
      </div>
    </section>
  );
}
